### PR TITLE
Typed messages

### PR DESCRIPTION
**Pull request by zaynyatyi**
Allows you to define desirable type of data which will be passed to handler
Like 
`var message = new TypedMessageType<Int>("message");`
And during compilation it will fire error if you will try to call 
`dispatchTyped(message, "string");`
instead of
`dispatchTyped(message, 1);`
It's backward compatible with current messages, so you can still use

```
addHandler(message, callback);
dispatch(message);
```

### CODE REVIEW

**Comment by grosmar** [comment]
Hello,

First of all thanks for the PR :)

We try to understand the real world usage of this solution. Can you write an example? 
How is it beneficial to tie your event type to the type that you will dispatch? 
And also how would it be possible to pass multiple parameters?

Thanks you!

**Comment by zaynyatyi** [comment]
The main benefit of that type of events is typed callbacks.
Currently (using regular MessageType) callback will get Array<Dynamic> and we will have to check if we get correct data, cast that data to desirable types.
With typed events you can define type of sending data directly in message.
For example

```
typedef UserData = {
  name:String;
  id:Int;
  password:String;
}

var message = new TypedMessageType<UserData>("userData");
dispatcher.addHandlerTyped(message, {}, handleUserData);

// Here we will get typed data
function handleUserData(data:UserData):Void
{
}
```

You can pack any typed and any amount of data using typedefs, classes or even containers (Maps and Arrays) to pass any amount of data.

So as a conclusion:
- if user will try to pass data using typed message system which is different from one which was defined in typed message compiler will raise error
- typed callback will get typed object, not just amount of dynamic data and there will be no need to parse it (check and cast)

**Comment by zaynyatyi** [comment]
Here is small gist with illustration https://gist.github.com/zaynyatyi/1a09179c8bf7eb0916845ea6a0294737

**Comment by zaynyatyi** [comment]
Basically that typed dispatches were created to remove data check on messages handlers (since currently it can be any Dynamic data) and move that check to compiler side :)

**Comment by aliokan** [comment]
not relevant anymore

**Pull request closed without merging**
